## ------------------------------------------------------------
## Top Nav Configuration
## This document contains configuration for the top nav sections
##
## ------------------------------------------------------------

- id: "articles"
  title: "Articles"
  url: "/get-started"
  folder: ""
  default: true

- id: "quickstarts"
  title: "Quickstarts"
  url: "/quickstarts"
  folder: "quickstart"

- id: "apis"
  title: "Auth0 APIs"
  url: "/api"
  folder: "api"

- id: "libraries"
  title: "Libraries"
  url: "/libraries"
  folder: "libraries"

- id: "videos"
  title: "Videos"
  url: "/videos"
  folder: "videos"

- id: "identity-labs"
  title: "Identity Labs"
  url: "/identity-labs"
  folder: "identity-labs"

- id: 'learn-the-basics'
  title: 'Learn the basics'
  url: '/learn-the-basics'
  folder: 'learn-the-basics'

- id: 'get-started'
  title: 'Get Started'
  url: '/get-started'
  folder: 'get-started'

- id: 'authenticate'
  title: 'Authenticate'
  url: '/authenticate'
  folder: 'authenticate'

- id: 'manage-users'
  title: 'Manage Users'
  url: '/manage-users'
  folder: 'manage-users'

- id: 'customization'
  title: 'Customize Auth0'
  url: '/customization'
  folder: 'customization'

- id: 'secure'
  title: 'Secure'
  url: '/secure'
  folder: 'secure'

- id: 'get-support'
  title: 'Get Support'
  url: '/get-support'
  folder: 'get-support'
