## ------------------------------------------------------------
## Top Nav Configuration
## This document contains configuration for the top nav sections
##
## ------------------------------------------------------------

- id: "articles"
  title: "Articles"
  url: "/get-started"
  folder: ""
  default: true

- id: "quickstarts"
  title: "Quickstarts"
  url: "/quickstarts"
  folder: "quickstart"

- id: "apis"
  title: "Auth0 APIs"
  url: "/api"
  folder: "api"

- id: "libraries"
  title: "Libraries"
  url: "/libraries"
  folder: "libraries"

- id: "videos"
  title: "Videos"
  url: "/videos"
  folder: "videos"

- id: "identity-labs"
  title: "Identity Labs"
  url: "/identity-labs"
  folder: "identity-labs"

- id: 'set-up'
  title: 'Set Up'
  url: '/set-up'
  folder: 'set-up'

- id: 'configuration'
  title: 'Configuration'
  url: '/configuration'
  folder: 'configuration'

- id: 'customization'
  title: 'Customization'
  url: '/customization'
  folder: 'customization'

- id: 'secure'
  title: 'Secure'
  url: '/secure'
  folder: 'secure'

- id: 'troubleshoot'
  title: 'Troubleshoot'
  url: '/troubleshoot'
  folder: 'troubleshoot'

- id: 'deploy'
  title: 'Deploy'
  url: '/deploy'
  folder: 'deploy'